# Generated by Django 5.1.5 on 2025-02-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=50)),
                ('example', models.TextField(blank=True, null=True)),
                ('tip', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
