# Generated by Django 5.1.5 on 2025-03-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='send_messages',
        ),
    ]
