# Generated by Django 5.1.5 on 2025-02-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('alphabet', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['id'], 'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='example',
            field=models.TextField(blank=True, null=True, verbose_name='Пример употребления'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='tip',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='translate',
            field=models.CharField(max_length=50, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='word',
            field=models.CharField(max_length=50, verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flashcards.category', verbose_name='Тема'),
        ),
    ]
