# Generated by Django 5.1.5 on 2025-03-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_advuser_delete_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
