# Generated by Django 5.1.5 on 2025-04-05 15:22

import flashcards.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_delete_advuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, upload_to=flashcards.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
